# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supermarket.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1015, 754)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        Frame.setLineWidth(5)
        self.frame = QtGui.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(70, 160, 341, 541))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 130, 281, 41))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 281, 51))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.listWidget = QtGui.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(30, 170, 281, 281))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 130, 141, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 130, 141, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(30, 170, 281, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(-3, 6, 81, 61))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../home/trustgodbro/Desktop/img_avatar2.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 20, 101, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_3.raise_()
        self.lineEdit_6.raise_()
        self.frame_6 = QtGui.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(30, 240, 281, 71))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_6 = QtGui.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(-3, 6, 81, 61))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../home/trustgodbro/Desktop/img_avatar5.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(170, 20, 101, 27))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(30, 310, 281, 71))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(-3, 6, 81, 61))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../home/trustgodbro/Desktop/img_avatar3.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 20, 101, 27))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_4.raise_()
        self.lineEdit_7.raise_()
        self.listWidget.raise_()
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(30, 380, 281, 71))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(-3, 6, 81, 61))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../home/trustgodbro/Desktop/img_avatar4.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(170, 20, 101, 27))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.listWidget.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.frame_3.raise_()
        self.frame_6.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.frame_2 = QtGui.QFrame(Frame)
        self.frame_2.setGeometry(QtCore.QRect(420, 160, 531, 541))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.treeWidget = QtGui.QTreeWidget(self.frame_2)
        self.treeWidget.setGeometry(QtCore.QRect(240, 130, 261, 291))
        self.treeWidget.setAutoScrollMargin(16)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 460, 113, 41))
        self.lineEdit_4.setStyleSheet(_fromUtf8("background-color: rgb(66, 183, 255);"))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(250, 460, 101, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 130, 201, 181))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../home/trustgodbro/Desktop/img_avatar2.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 60, 201, 51))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 60, 261, 51))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(Frame)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 40, 891, 71))
        self.pushButton_6.setStyleSheet(_fromUtf8("color: rgb(35, 141, 255);\n"
"font: 75 14pt \"Ubuntu\";"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Supermarket DashBoard", None))
        self.lineEdit_2.setText(_translate("Frame", "                         ", None))
        self.pushButton.setText(_translate("Frame", "List of Customers", None))
        self.pushButton_2.setText(_translate("Frame", "Customer-Image", None))
        self.pushButton_3.setText(_translate("Frame", "Total price", None))
        self.lineEdit_6.setText(_translate("Frame", "20000", None))
        self.lineEdit_9.setText(_translate("Frame", "5000", None))
        self.lineEdit_7.setText(_translate("Frame", "5000", None))
        self.lineEdit_8.setText(_translate("Frame", "20000", None))
        self.treeWidget.headerItem().setText(0, _translate("Frame", "items", None))
        self.treeWidget.headerItem().setText(1, _translate("Frame", "Price", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Frame", "Margarine", None))
        self.treeWidget.topLevelItem(0).setText(1, _translate("Frame", "25000", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Frame", "Coke", None))
        self.treeWidget.topLevelItem(1).setText(1, _translate("Frame", "2000", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Frame", "Lato Milk", None))
        self.treeWidget.topLevelItem(2).setText(1, _translate("Frame", "12000", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Frame", "Cup", None))
        self.treeWidget.topLevelItem(3).setText(1, _translate("Frame", "1500", None))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Frame", "item1", None))
        self.treeWidget.topLevelItem(4).setText(1, _translate("Frame", "1000", None))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Frame", "Banana", None))
        self.treeWidget.topLevelItem(5).setText(1, _translate("Frame", "500", None))
        self.treeWidget.topLevelItem(6).setText(0, _translate("Frame", "Mango", None))
        self.treeWidget.topLevelItem(6).setText(1, _translate("Frame", "300", None))
        self.treeWidget.topLevelItem(7).setText(0, _translate("Frame", "Ice Cream", None))
        self.treeWidget.topLevelItem(7).setText(1, _translate("Frame", "1250", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_4.setText(_translate("Frame", "50000", None))
        self.label_2.setText(_translate("Frame", "TOTAL PRICE", None))
        self.pushButton_4.setText(_translate("Frame", "Customer-Image", None))
        self.pushButton_5.setText(_translate("Frame", "List of item Taken", None))
        self.pushButton_6.setText(_translate("Frame", "AUTOMATIC PRICE DETECTION SYSTEM ", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Frame = QtGui.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

